name: Regenerate Repository Database

on:
  workflow_dispatch:

jobs:
  regenerate-repo-db:
    runs-on: ubuntu-latest
    container:
     image: archlinux:base-devel
     volumes:
        - ${{ github.workspace }}:/root
    steps:
      - name: Update Package DB
        run: |
          pacman-key --init
          pacman-key --populate
          pacman -Syu --noconfirm wget jq
          for url in $(curl -s https://api.github.com/repos/Bryan2333/xanmod-for-arch/releases/latest | jq -r '.assets[].browser_download_url')
          do
              wget --quiet "$url"
          done
          rm -rf xanmod*
          repo-add -n xanmod.db.tar.xz *.pkg.tar.*
      - name: Upload database to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/xanmod*
          tag_name: packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
